### ISSUE TITLE
Compile into a binary executable, make a release

### ISSUE THREAD

**Issue by rcswex** [Independent-Dreamer/virtual_piano#1]
It needs to be introduced to more people. Not everyone knows how to run python, and I reported an error when I installed pygame myself, system permissions do not allow it. The software is now fully functional, the details of the adjustment, program settings, etc. can first follow the default, or directly write an .ini file to contain the settings items. It is recommended to compile into a binary executable and do a release, the version can be taken as v0.5 or something like that. The most important thing is to let more people use it and understand it.

需要介绍给更多的人使用。并不是所有人都懂运行 python，而且我自己安装 pygame 库时就报出错，系统权限不允许。该软件目前功能已完整，细节的调整、程序设置等可以先按照默认，或者直接写一个 .ini 文件装载设置项目。建议编译成二进制可执行文件，做一个 release，版本可以取 v0.5 之类。最重要的是让更多人使用它和了解它。

**Comment by Independent-Dreamer** [comment]
好的，感谢建议！

**Comment by beibao233** [comment]
This issue should be closed ASAP.

> 好的，感谢建议！

**Comment by beibao233** [comment]
> 好的，感谢建议！

Bro, you closed my unsolved issues but keep this finished one. What gives?
