### ISSUE TITLE
The note rendering termination failure when using external MIDI input (Yamaha ARIUS YDP-165)

### ISSUE THREAD

**Issue by beibao233** [Independent-Dreamer/virtual_piano#2]
![4(0GCG9QPL3FMXR ~9GG2R6](https://github.com/Independent-Dreamer/virtual_piano/assets/63646638/b9fb0837-a5ec-47cf-810c-5a4806e9aeaf)
 As the picture goes, you can tell that some notes aren't closing as expected.
 
 I have tried both your publishment and source code, and they both have the same issues.
 Based on my experience in other projects, the problem is very likely involved with your note-rendering thread or object.
 
 I have reviewed your code roughly, and notice that it seems you have some challenges during the process of programming.
 I can help you make a reversion of the project, please let me know if you are interested.

**Comment by Independent-Dreamer** [comment]
Thank you for your feedback. I didn’t have any relevant project experience before, so this project does have some issues. But unfortunately, I have been busy preparing for the postgraduate entrance exam and graduation project recently, so I haven’t updated it for a long time. After I finish my current tasks, if I have time, I would also like to contact you further. Thank you!

**Comment by Independent-Dreamer** [comment]
Thank you for your feedback. I didn’t have any relevant project experience before, so this project does have some issues. But unfortunately, I have been busy preparing for the postgraduate entrance exam and graduation project recently, so I haven’t updated it for a long time. After I finish my current tasks, if I have time, I would also like to contact you further. Thank you!

**Comment by beibao233** [comment]
What the heck, it didn't solve anything.

**Comment by Independent-Dreamer** [comment]
Thank you for your feedback. I didn’t have any relevant project experience before, so this project does have some issues. But unfortunately, I have been busy preparing for the postgraduate entrance exam and graduation project recently, so I haven’t updated it for a long time. After I finish my current tasks, if I have time, I would also like to contact you further. Thank you!

**Comment by beibao233** [comment]
> Thank you for your feedback. I didn’t have any relevant project experience before, so this project does have some issues. But unfortunately, I have been busy preparing for the postgraduate entrance exam and graduation project recently, so I haven’t updated it for a long time. After I finish my current tasks, if I have time, I would also like to contact you further. Thank you!
              This issue should be closed ASAP.

> 好的，感谢建议！

_Originally posted by @beibao233 in https://github.com/Independent-Dreamer/virtual_piano/issues/1#issuecomment-1908116531_
 *Don't forget to close this.

I understand. I wish you good luck in entrance and a happy new year.

My QQ number is 2784535931, and the answer to the friend request question is "什么". 
We can add a friend if you want :-D
